-- =====================================================================
-- SQUAD PLAYERS WITH PHOTOS — BATCH 2
-- Kanamai FC, Zion FC, Baraza FC, Mtepeni United, Komboa FC
-- Run AFTER supabase/player-photos.sql and squad-photos-batch1.sql.
--
-- Kanamai, Zion, Baraza: matched by exact position in a verified,
-- regular photo grid (confirmed count match + visual spot-checks
-- across multiple rows/columns).
--
-- Komboa: one name ("Kenneth Otieno") appeared twice in the source
-- sheet with the exact same photo both times — a genuine duplicate in
-- their paperwork, not two players — so it's listed once here. The
-- two "Fredrick Oduor" entries ARE two different people (confirmed by
-- comparing their photos), so both are kept. One player, Micheal
-- Otieno, has no photo — his entry in the source PDF didn't have a
-- separately embedded image, so he's added name-only (shows as
-- initials on the site, same as any player without a photo).
-- =====================================================================

INSERT INTO squads (club_id, player_name, photo_url) VALUES
  ('kanamai', 'Michael Haro',     'assets/players/kanamai/000.jpg'),
  ('kanamai', 'Mourice Nyundo',   'assets/players/kanamai/001.jpg'),
  ('kanamai', 'Ali Ali',          'assets/players/kanamai/002.jpg'),
  ('kanamai', 'Rashid George',    'assets/players/kanamai/003.jpg'),
  ('kanamai', 'Alfred Mkare',     'assets/players/kanamai/004.jpg'),
  ('kanamai', 'Prince Tangai',    'assets/players/kanamai/005.jpg'),
  ('kanamai', 'Sheban Said',      'assets/players/kanamai/006.jpg'),
  ('kanamai', 'Delvis Kaingu',    'assets/players/kanamai/007.jpg'),
  ('kanamai', 'Alex Kifaru',      'assets/players/kanamai/008.jpg'),
  ('kanamai', 'Yusuf Mohame',     'assets/players/kanamai/009.jpg'),
  ('kanamai', 'Joshua Kante',     'assets/players/kanamai/010.jpg'),
  ('kanamai', 'Fesual Mabula',    'assets/players/kanamai/011.jpg'),
  ('kanamai', 'Francis Star',     'assets/players/kanamai/012.jpg'),
  ('kanamai', 'Eric Vitembo',     'assets/players/kanamai/013.jpg'),
  ('kanamai', 'Julius Chenjele',  'assets/players/kanamai/014.jpg'),
  ('kanamai', 'Bernard Deche',    'assets/players/kanamai/015.jpg'),
  ('kanamai', 'Ali Chinga',       'assets/players/kanamai/016.jpg'),
  ('kanamai', 'Kelvin Masha',     'assets/players/kanamai/017.jpg'),
  ('kanamai', 'Papah Kotela',     'assets/players/kanamai/018.jpg'),
  ('kanamai', 'Mohammed Juma',    'assets/players/kanamai/019.jpg'),
  ('kanamai', 'Emmanuel Yeri',    'assets/players/kanamai/020.jpg'),
  ('kanamai', 'Philip Kitola',    'assets/players/kanamai/021.jpg'),

  ('zion', 'Kelvin Mwasambu',    'assets/players/zion/00.jpg'),
  ('zion', 'Richard Kalenga',    'assets/players/zion/01.jpg'),
  ('zion', 'Harun Mauka',        'assets/players/zion/02.jpg'),
  ('zion', 'Frankline Ngala',    'assets/players/zion/03.jpg'),
  ('zion', 'Morris Runya',       'assets/players/zion/04.jpg'),
  ('zion', 'Nicholus Mwakamba',  'assets/players/zion/05.jpg'),
  ('zion', 'Mackson Mwakamba',   'assets/players/zion/06.jpg'),
  ('zion', 'Erick Kalama',       'assets/players/zion/07.jpg'),
  ('zion', 'Jonathani Rimba',    'assets/players/zion/08.jpg'),
  ('zion', 'Frankline Jilani',   'assets/players/zion/09.jpg'),
  ('zion', 'Chodah Wanje',       'assets/players/zion/10.jpg'),
  ('zion', 'George Mwalungo',    'assets/players/zion/11.jpg'),
  ('zion', 'Noel Mwachiru',      'assets/players/zion/12.jpg'),
  ('zion', 'Mackson Baya',       'assets/players/zion/13.jpg'),
  ('zion', 'Jonathan Washe',     'assets/players/zion/14.jpg'),
  ('zion', 'Franklin Janji',     'assets/players/zion/15.jpg'),
  ('zion', 'Alex Tandiko',       'assets/players/zion/16.jpg'),
  ('zion', 'Kelvin Washe',       'assets/players/zion/17.jpg'),
  ('zion', 'Micheal Mganga',     'assets/players/zion/18.jpg'),
  ('zion', 'Rama Janji',         'assets/players/zion/19.jpg'),

  ('baraza', 'Paul Baraka',        'assets/players/baraza/00.jpg'),
  ('baraza', 'Andrew Juma',        'assets/players/baraza/01.jpg'),
  ('baraza', 'Ahmed Ali',          'assets/players/baraza/02.jpg'),
  ('baraza', 'Beka Nyamawi',       'assets/players/baraza/03.jpg'),
  ('baraza', 'Elijah Katana',      'assets/players/baraza/04.jpg'),
  ('baraza', 'Rumba Junior',       'assets/players/baraza/05.jpg'),
  ('baraza', 'Sammy Junior',       'assets/players/baraza/06.jpg'),
  ('baraza', 'Omar Katana',        'assets/players/baraza/07.jpg'),
  ('baraza', 'Erick Washe',        'assets/players/baraza/08.jpg'),
  ('baraza', 'Ali Mnyika',         'assets/players/baraza/09.jpg'),
  ('baraza', 'Salim Henry',        'assets/players/baraza/10.jpg'),
  ('baraza', 'Chenko Kithi',       'assets/players/baraza/11.jpg'),
  ('baraza', 'Baraka Emmanuel',    'assets/players/baraza/12.jpg'),
  ('baraza', 'Justin Safari',      'assets/players/baraza/13.jpg'),
  ('baraza', 'Hussein Bedui',      'assets/players/baraza/14.jpg'),
  ('baraza', 'Jackson Malanga',    'assets/players/baraza/15.jpg'),
  ('baraza', 'Warren Clement',     'assets/players/baraza/16.jpg'),
  ('baraza', 'Abel Kalu',          'assets/players/baraza/17.jpg'),
  ('baraza', 'Kitsao Nyamawi',     'assets/players/baraza/18.jpg'),
  ('baraza', 'Joshua Kimmich',     'assets/players/baraza/19.jpg'),
  ('baraza', 'Mark Mkare',         'assets/players/baraza/20.jpg'),
  ('baraza', 'Wilson Kalu',        'assets/players/baraza/21.jpg'),
  ('baraza', 'Nzai Chilumo',       'assets/players/baraza/22.jpg'),
  ('baraza', 'Sylvester Jackson',  'assets/players/baraza/23.jpg'),
  ('baraza', 'Evans Baraka',       'assets/players/baraza/24.jpg'),

  ('mtepeni', 'Amos Zaka',        'assets/players/mtepeni/000.jpg'),
  ('mtepeni', 'Rodgers Nyundo',   'assets/players/mtepeni/001.jpg'),
  ('mtepeni', 'Steven Kombo',     'assets/players/mtepeni/002.jpg'),
  ('mtepeni', 'Fahil Abdul',      'assets/players/mtepeni/003.jpg'),
  ('mtepeni', 'Mohamed Ngumbao',  'assets/players/mtepeni/004.jpg'),
  ('mtepeni', 'Charles Matsaki',  'assets/players/mtepeni/005.jpg'),
  ('mtepeni', 'Kelly Ndoro',      'assets/players/mtepeni/006.jpg'),
  ('mtepeni', 'Bosco Mwangale',   'assets/players/mtepeni/007.jpg'),
  ('mtepeni', 'Ali Lewa',         'assets/players/mtepeni/008.jpg'),
  ('mtepeni', 'Estevao Kingi',    'assets/players/mtepeni/009.jpg'),
  ('mtepeni', 'Jackson Lugo',     'assets/players/mtepeni/010.jpg'),
  ('mtepeni', 'Rado Chuma',       'assets/players/mtepeni/011.jpg'),
  ('mtepeni', 'Manu Ngari',       'assets/players/mtepeni/012.jpg'),
  ('mtepeni', 'Tyres Kabugo',     'assets/players/mtepeni/013.jpg'),

  ('komboa', 'Bakari Khamis',    'assets/players/komboa/000.jpg'),
  ('komboa', 'Kenneth Otieno',   'assets/players/komboa/001.jpg'),
  ('komboa', 'Luka Mdungu',      'assets/players/komboa/002.jpg'),
  ('komboa', 'Adrian Kilonzo',   'assets/players/komboa/003.jpg'),
  ('komboa', 'Kwaka Bora',       'assets/players/komboa/004.jpg'),
  ('komboa', 'Martin Okumu',     'assets/players/komboa/005.jpg'),
  ('komboa', 'Kingi Kitsao',     'assets/players/komboa/006.jpg'),
  ('komboa', 'Juma Kombo',       'assets/players/komboa/007.jpg'),
  ('komboa', 'Brian Kazungu',    'assets/players/komboa/008.jpg'),
  ('komboa', 'Joseph Saidi',     'assets/players/komboa/009.jpg'),
  ('komboa', 'Evans Oweke',      'assets/players/komboa/010.jpg'),
  ('komboa', 'Brian Zakayo',     'assets/players/komboa/011.jpg'),
  ('komboa', 'Jackbret Omondi',  'assets/players/komboa/012.jpg'),
  ('komboa', 'Appiah Garama',    'assets/players/komboa/013.jpg'),
  ('komboa', 'Ali Salim',        'assets/players/komboa/014.jpg'),
  ('komboa', 'Justin Kazungu',   'assets/players/komboa/015.jpg'),
  ('komboa', 'Benson Rashid',    'assets/players/komboa/017.jpg'),
  ('komboa', 'Tajong Tajocha',   'assets/players/komboa/018.jpg'),
  ('komboa', 'Vitalis Baraza',   'assets/players/komboa/019.jpg'),
  ('komboa', 'Evans Oluoch',     'assets/players/komboa/020.jpg'),
  ('komboa', 'Ezrono Odao',      'assets/players/komboa/021.jpg'),
  ('komboa', 'Dominic Odhiambo', 'assets/players/komboa/022.jpg'),
  ('komboa', 'Clement Ondifu',   'assets/players/komboa/023.jpg'),
  ('komboa', 'Tobias Ouma',      'assets/players/komboa/024.jpg'),
  ('komboa', 'Jared Otieno',     'assets/players/komboa/025.jpg'),
  ('komboa', 'Johnmovine On',    'assets/players/komboa/026.jpg'),
  ('komboa', 'Macline Og',       'assets/players/komboa/027.jpg'),
  ('komboa', 'Didah Khamisi',    'assets/players/komboa/028.jpg'),
  ('komboa', 'Fredrick Oduor',   'assets/players/komboa/029.jpg'),
  ('komboa', 'Fredrick Oduor',   'assets/players/komboa/030.jpg'),
  ('komboa', 'Fadhili Khamisi',  'assets/players/komboa/031.jpg'),
  ('komboa', 'Lamex Johns',      'assets/players/komboa/032.jpg'),
  ('komboa', 'Brian Ouma',       'assets/players/komboa/033.jpg'),
  ('komboa', 'Micheal Otieno',   NULL);
