-- =====================================================================
-- MTWAPA PREMIER LEAGUE — SEED DATA
-- Run this AFTER schema.sql, in the same SQL Editor.
-- Loads your current real club/table/fixtures/scorers/squads/news data
-- so the site looks exactly like it does now once you switch it over.
-- =====================================================================

-- CLUBS
INSERT INTO clubs (id, name, venue) VALUES
  ('travellers', 'Travellers FC', NULL),
  ('bahariutd', 'Bahari United FC', 'Kanamai'),
  ('mgandini', 'Mgandini FC', 'Divers'),
  ('mvitaoil', 'Mvita Oil FC', 'Mtomondoni'),
  ('laliga', 'La Liga FC', 'KP Mtwapa'),
  ('fuhua', 'Fuhua FC', 'Mtomondoni'),
  ('mtwapaseniors', 'Mtwapa Seniors FC', 'Vipingo'),
  ('revolution', 'Revolution FC', 'Shanzu'),
  ('kicks', 'Kicks FC', 'Vipingo'),
  ('kanamai', 'Kanamai FC', 'Kanamai'),
  ('fullsun', 'Fullsun Rangers FC', 'Bodoi'),
  ('bomaniyouth', 'Bomani Youth FC', 'Bodoi'),
  ('progressive', 'Progressive FC', 'Kanamai'),
  ('mpatempate', 'Mpate Mpate FC', 'Vipingo'),
  ('kimbunga', 'Kimbunga FC', 'Kanamai'),
  ('kilifiteachers', 'Kilifi Teachers FC', 'Vipingo Cross'),
  ('youngheroes', 'Young Heroes FC', 'KP Mtwapa'),
  ('zion', 'Zion FC', 'Kanamai'),
  ('ama4', 'AMA-4 FC', 'Kanamai'),
  ('majaoni', 'Majaoni Young Stars FC', 'Annex'),
  ('dola', 'Dola FC', 'Divers'),
  ('komboa', 'Komboa FC', 'KP Mtwapa'),
  ('sunset', 'Sunset FC', 'Bomani'),
  ('mtepeni', 'Mtepeni FC', 'Bomani'),
  ('mega', 'Mega FC', 'Bomani'),
  ('newtalent', 'New Talent FC', NULL),
  ('ambassadors', 'Ambassadors FC', 'KP Mtwapa'),
  ('posterrangers', 'Poster Rangers FC', 'Bodoi'),
  ('mtwapaallstars', 'Mtwapa Allstars FC', 'KP Mtwapa'),
  ('mikanjuni', 'Mikanjuni FC', 'KP Mtwapa'),
  ('baraza', 'Baraza FC', 'Bomani');

-- TABLE ROWS
INSERT INTO table_rows (club_id, p, w, d, l, gf, ga) VALUES
  ('travellers', 9, 9, 0, 0, 20, 0),
  ('bahariutd', 10, 7, 0, 3, 23, 8),
  ('mgandini', 9, 6, 2, 1, 11, 5),
  ('mvitaoil', 9, 6, 1, 2, 18, 6),
  ('laliga', 9, 6, 1, 2, 18, 8),
  ('fuhua', 9, 5, 3, 1, 10, 4),
  ('mtwapaseniors', 8, 5, 2, 1, 14, 7),
  ('revolution', 8, 5, 1, 2, 14, 10),
  ('kicks', 8, 4, 2, 2, 16, 6),
  ('kanamai', 7, 4, 2, 1, 16, 10),
  ('fullsun', 8, 4, 2, 2, 15, 10),
  ('bomaniyouth', 9, 4, 2, 3, 11, 10),
  ('progressive', 9, 3, 3, 3, 12, 7),
  ('mpatempate', 8, 3, 3, 2, 8, 7),
  ('kimbunga', 8, 2, 5, 1, 10, 8),
  ('kilifiteachers', 8, 3, 2, 3, 13, 12),
  ('youngheroes', 9, 3, 2, 4, 11, 14),
  ('zion', 9, 3, 1, 5, 13, 12),
  ('ama4', 8, 3, 1, 4, 9, 11),
  ('majaoni', 8, 3, 1, 4, 8, 11),
  ('dola', 7, 2, 2, 3, 12, 16),
  ('komboa', 10, 2, 2, 6, 9, 17),
  ('sunset', 9, 2, 2, 5, 8, 17),
  ('mtepeni', 8, 1, 4, 3, 10, 14),
  ('mega', 8, 2, 1, 5, 6, 21),
  ('newtalent', 7, 2, 0, 5, 9, 14),
  ('ambassadors', 9, 1, 3, 5, 7, 14),
  ('posterrangers', 9, 2, 0, 7, 10, 21),
  ('mtwapaallstars', 9, 1, 2, 6, 9, 20),
  ('mikanjuni', 9, 1, 1, 7, 10, 19),
  ('baraza', 9, 1, 1, 7, 5, 26);

-- SCORERS
INSERT INTO scorers (player_name, club_id, goals) VALUES
  ('Phidel Onyango', 'mvitaoil', 8),
  ('Walter Ichela', 'mtwapaseniors', 7),
  ('Jackson Kabaka', 'bahariutd', 6),
  ('Athman', 'progressive', 5),
  ('Remi Kenga', 'travellers', 5),
  ('Ibra Nyanje', 'laliga', 5),
  ('Steven David', 'revolution', 5),
  ('Bernard Deche', 'kanamai', 5),
  ('Austerious Wafula', 'fuhua', 4),
  ('Amani Chengo', 'laliga', 4),
  ('Omar Abdalla', 'kicks', 4),
  ('Lucky Rajab', 'mikanjuni', 4),
  ('Maxwell Muye', 'zion', 4),
  ('Victor Chege', 'mega', 4),
  ('Baraka Chicha', 'mgandini', 4),
  ('Rophus Mlanda', 'kimbunga', 4),
  ('Quinton Kambu', 'revolution', 3),
  ('Mackson Sanga', 'zion', 3),
  ('Victor Shoboi', 'progressive', 3),
  ('Sammy Ngala', 'sunset', 3),
  ('Salim Abae', 'kilifiteachers', 3),
  ('Kingi Kitsao', 'komboa', 3),
  ('James Dede', 'bahariutd', 3),
  ('Kelvin Ngumbao', 'bomaniyouth', 3),
  ('Ali Chinga', 'kanamai', 3),
  ('Andreah Fahari', 'youngheroes', 3),
  ('Shebani Mwagandi', 'laliga', 3),
  ('Rama Chengo', 'fullsun', 3),
  ('George Bora', 'fullsun', 3),
  ('Hashim Kithi', 'fullsun', 3);

-- FIXTURES
INSERT INTO fixtures (id, match_no, date, home_id, away_id, venue, kickoff) VALUES
  ('m120', '120', '2026-08-01', 'laliga', 'mtepeni', 'KP Mtwapa', '15:00'),
  ('m121', '121', '2026-08-01', 'mtwapaallstars', 'mvitaoil', 'Mtomondoni', '15:00'),
  ('m122', '122', '2026-08-01', 'progressive', 'bahariutd', 'Kanamai', '15:00'),
  ('m123', '123', '2026-08-01', 'komboa', 'zion', 'Kari', '15:00'),
  ('m124', '124', '2026-08-01', 'mgandini', 'mtwapaseniors', 'Divers', '15:00'),
  ('m125', '125', '2026-08-01', 'sunset', 'baraza', 'Bomani', '15:00'),
  ('m126', '126', '2026-08-02', 'mikanjuni', 'fullsun', 'KP Mtwapa', '13:00'),
  ('m127', '127', '2026-08-02', 'revolution', 'ambassadors', 'KP Mtwapa', '15:00'),
  ('m128', '128', '2026-08-02', 'kanamai', 'kimbunga', 'Kanamai', '15:00'),
  ('m129', '129', '2026-08-02', 'kilifiteachers', 'ama4', 'Vipingo Cross', '15:00'),
  ('m130', '130', '2026-08-02', 'youngheroes', 'fuhua', 'Mtomondoni', '15:00'),
  ('m131', '131', '2026-08-02', 'mpatempate', 'travellers', 'Vipingo', '15:00'),
  ('m132', '132', '2026-08-02', 'posterrangers', 'bomaniyouth', 'Bodoi', '15:00'),
  ('m133', '133', '2026-08-02', 'mega', 'kicks', 'Bomani', '15:00'),
  ('m134', '134', '2026-08-02', 'majaoni', 'dola', 'Annex', '15:00'),
  ('m135', '135', '2026-08-08', 'mtwapaallstars', 'posterrangers', 'KP Mtwapa', '15:00'),
  ('m136', '136', '2026-08-08', 'bomaniyouth', 'progressive', 'Kanamai', '15:00'),
  ('m137', '137', '2026-08-08', 'ambassadors', 'laliga', 'Divers', '15:00'),
  ('m138', '138', '2026-08-08', 'mtwapaseniors', 'bahariutd', 'Vipingo', '15:00'),
  ('m139', '139', '2026-08-08', 'travellers', 'revolution', 'Shanzu', '15:00'),
  ('m140', '140', '2026-08-08', 'mtepeni', 'majaoni', 'Bomani', '15:00'),
  ('m141', '141', '2026-08-09', 'youngheroes', 'mgandini', 'KP Mtwapa', '09:00'),
  ('m142', '142', '2026-08-09', 'mvitaoil', 'mikanjuni', 'KP Mtwapa', '13:00'),
  ('m143', '143', '2026-08-09', 'baraza', 'komboa', 'KP Mtwapa', '15:00'),
  ('m144', '144', '2026-08-09', 'mega', 'mpatempate', 'Bomani', '15:00'),
  ('m145', '145', '2026-08-09', 'ama4', 'zion', 'Kanamai', '15:00'),
  ('m146', '146', '2026-08-09', 'fuhua', 'sunset', 'Mtomondoni', '15:00'),
  ('m147', '147', '2026-08-09', 'kilifiteachers', 'kicks', 'Vipingo', '15:00'),
  ('m148', '148', '2026-08-09', 'fullsun', 'kanamai', 'Bodoi', '15:00'),
  ('m149', '149', '2026-08-09', 'dola', 'kimbunga', 'Divers', '15:00');

-- SQUADS
INSERT INTO squads (club_id, player_name, jersey_no) VALUES
  ('komboa', 'Bakari Khamis', 1),
  ('komboa', 'Kenneth Otieno', 2),
  ('komboa', 'Luka Mdungu', 3),
  ('komboa', 'Adrian Kilonzo', 4),
  ('komboa', 'Kwaka Bora', 5),
  ('komboa', 'Martin Okumu', 6),
  ('komboa', 'Kingi Kitsao', 7),
  ('komboa', 'Juma Kombo', 8),
  ('komboa', 'Brian Kazungu', 9),
  ('komboa', 'Joseph Saidi', 10),
  ('komboa', 'Evans Oweke', 11),
  ('komboa', 'Brian Zakayo', 12),
  ('komboa', 'Jackbret Omondi', 13),
  ('komboa', 'Appiah Garama', 14),
  ('komboa', 'Ali Salim', 15),
  ('komboa', 'Justin Kazungu', 16),
  ('komboa', 'Benson Rashid', 17),
  ('komboa', 'Tajong Tajocha', 18),
  ('komboa', 'Vitalis Baraza', 19),
  ('komboa', 'Evans Oluoch', 20),
  ('komboa', 'Ezrono Odao', 21),
  ('komboa', 'Dominic Odhiambo', 22),
  ('komboa', 'Clement Ondifu', 23),
  ('komboa', 'Tobias Ouma', 24),
  ('komboa', 'Jared Otieno', 25),
  ('komboa', 'Didah Khamisi', 26),
  ('komboa', 'Fredrick Oduor', 27),
  ('komboa', 'Fadhili Khamisi', 28),
  ('komboa', 'Lamex Johns', 29),
  ('komboa', 'Brian Ouma', 30),
  ('komboa', 'Micheal Otieno', 31),
  ('bomaniyouth', 'Juma Yaa', 1),
  ('bomaniyouth', 'Isaac Washe', 2),
  ('bomaniyouth', 'Hassan Toya', 3),
  ('bomaniyouth', 'Saliba Harrison', 4),
  ('bomaniyouth', 'Jole Timber', 5),
  ('bomaniyouth', 'Kelvin Ngumbao', 6),
  ('bomaniyouth', 'Jude Mohah', 7),
  ('bomaniyouth', 'Rajab Dzimba', 8),
  ('bomaniyouth', 'Simon Lewa', 9),
  ('bomaniyouth', 'Alex JJ', 10),
  ('bomaniyouth', 'Brighton Hamisi', 11),
  ('bomaniyouth', 'Brian Ngala', 12),
  ('bomaniyouth', 'Lucky John', 13),
  ('bomaniyouth', 'Timothy Nyale', 14),
  ('bomaniyouth', 'Paul Katana', 15),
  ('bomaniyouth', 'Jimmy Kalenga', 16),
  ('bomaniyouth', 'Elias Kalume', 17),
  ('bomaniyouth', 'Syzen Kazungu', 18),
  ('bomaniyouth', 'Mohamed Muhsin', 19),
  ('bomaniyouth', 'Shylock Jefwa', 20),
  ('bomaniyouth', 'Denis Ndoro', 21),
  ('bomaniyouth', 'Gideon Ngundo', 22),
  ('bomaniyouth', 'Rafael Juma', 23),
  ('bomaniyouth', 'Enock Mweri', 24),
  ('bomaniyouth', 'Stallon Gunga', 25),
  ('bomaniyouth', 'Saul Katana', 26),
  ('bomaniyouth', 'Lemmy Kubamba', 27),
  ('bomaniyouth', 'Dhuka Dhuka', 28),
  ('bomaniyouth', 'Hamid Athman', 29),
  ('bomaniyouth', 'Ngwenje Khamisi', 30),
  ('fuhua', 'Huncho Joshua', 1),
  ('fuhua', 'Elvis Odero', 2),
  ('fuhua', 'Ondulo Otsula', 3),
  ('fuhua', 'Anthony Pepez', 4),
  ('fuhua', 'Elija Zushi', 5),
  ('fuhua', 'Ray K.D.B', 6),
  ('fuhua', 'Amin Jeffa', 7),
  ('fuhua', 'Raphael Omollo', 8),
  ('fuhua', 'Noman Wafula', 9),
  ('fuhua', 'Steve Okutaa', 10),
  ('fuhua', 'Syllas Ouma', 11),
  ('fuhua', 'Suleiman Jnr', 12),
  ('fuhua', 'Yussuf Ziro', 13),
  ('fuhua', 'Erick Jombaa', 14),
  ('fuhua', 'Davii Jnr', 15),
  ('fuhua', 'John Mwanja', 16),
  ('fuhua', 'David Ouru', 17),
  ('fuhua', 'Jay Ndichu', 18),
  ('fuhua', 'Wekesa Jr', 19),
  ('fuhua', 'E. Manucho', 20),
  ('fuhua', 'Johnte Simiyu', 21),
  ('fuhua', 'Astee Wafula', 22),
  ('fuhua', 'Luck Masha', 23),
  ('fuhua', 'Ramaa Hassan', 24),
  ('progressive', 'Joseph Kazengo', 1),
  ('progressive', 'George Katana', 2),
  ('progressive', 'Alphonce Onduru', 3),
  ('progressive', 'Mohamed Chai', 4),
  ('progressive', 'Victor Shoboi', 5),
  ('progressive', 'Jabir Mahadhi', 6),
  ('progressive', 'Samir Mohamed', 7),
  ('progressive', 'Imarn Mahadhi', 8),
  ('progressive', 'Steven Yaa', 9),
  ('progressive', 'Arafat Askul', 10),
  ('progressive', 'Athman Mohamed', 11),
  ('progressive', 'Reymond Kahindi', 12),
  ('progressive', 'Mohamed Kurera', 13),
  ('progressive', 'Alex Murage', 14),
  ('progressive', 'Austeen Rimba', 15),
  ('progressive', 'Christopher Kim', 16),
  ('progressive', 'Abdallah Mwarua', 17),
  ('progressive', 'Omar Salim', 18),
  ('progressive', 'Abdallah Abdallah', 19),
  ('progressive', 'Vincent Chengo', 20),
  ('progressive', 'Hance Douglas', 21),
  ('progressive', 'Harun Mazeras', 22),
  ('progressive', 'Galole', 23),
  ('progressive', 'Daniel Steve', 24),
  ('progressive', 'Fuad Mohammed', 25),
  ('progressive', 'Joshua Gona', 26),
  ('kicks', 'Austine Odhiambo', 1),
  ('kicks', 'Lonnex Kesi', 2),
  ('kicks', 'Kelvin Charo', 3),
  ('kicks', 'Anthony Mwango', 4),
  ('kicks', 'Khalid Suleiman', 5),
  ('kicks', 'Juma Ali', 6),
  ('kicks', 'Steve Ondiek', 7),
  ('kicks', 'Patrick Kambi', 8),
  ('kicks', 'Mike Wangura', 9),
  ('kicks', 'Daddy Bora', 10),
  ('kicks', 'Musa Charo', 11),
  ('kicks', 'Joseph Okumu', 12),
  ('kicks', 'Buki Issa', 13),
  ('kicks', 'Omari Rashid', 14),
  ('kicks', 'Evans Katana', 15),
  ('kicks', 'Elington Boss', 16),
  ('kicks', 'Gilbert Thomas', 17),
  ('kicks', 'Yussuf Moha', 18),
  ('kicks', 'Anthony Bora', 19),
  ('kicks', 'Samuel Ngoja', 20),
  ('kicks', 'Sande Katana', 21),
  ('kicks', 'Franco Ndago', 22),
  ('kicks', 'Daniel Melo', 23),
  ('kicks', 'Moha Ali', 24),
  ('kicks', 'Pascal Gakpo', 25),
  ('kicks', 'Henry Jagabi', 26),
  ('kicks', 'Martin Mwaganda', 27),
  ('kicks', 'Rophus Roro', 28),
  ('kicks', 'Renson Matonya', 29),
  ('kicks', 'Sammy Katana', 30),
  ('kicks', 'Baraka Mwango', 31),
  ('kicks', 'Arnold Makau', 32);

-- SETTINGS
UPDATE settings SET season_label = 'Season 2026 — 5th Edition', as_of_label = 'as at August 2026' WHERE id = 1;

-- NEWS
INSERT INTO news (tag, title, body) VALUES
  ('League Table', 'Travellers FC unbeaten at the top of the Mtwapa Premier League', 'Travellers FC lead the table with 27 points from 9 played, having won every match so far this season.'),
  ('Golden Boot', 'Phidel Onyango leads the race for the Golden Boot', 'Phidel Onyango of Mvita Oil FC tops the Mtwapa Premier League scoring charts with 8 goals as at August 2026.'),
  ('Title Race', 'Bahari United FC chase down the leaders', 'Bahari United FC sit second on 21 points, 6 adrift of top spot, as the race for the title continues.'),
  ('Bottom of the Table', 'Fight for survival intensifies at the foot of the table', 'Baraza FC currently prop up the 31-team table, with results across the bottom half still tight enough to change on any given matchday.'),
  ('Fixtures', 'August fixture programme in full swing', 'Matchweek fixtures continue across venues including KP Mtwapa, Kanamai, Bomani, Vipingo and Divers, with 26 clubs contesting a packed August schedule.');