/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as ScorersRouteImport } from './routes/scorers'
import { Route as TableRouteImport } from './routes/table'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorersRoute = ScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/predictor': typeof PredictorRoute
  '/scorers': typeof ScorersRoute
  '/table': typeof TableRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/predictor': typeof PredictorRoute
  '/scorers': typeof ScorersRoute
  '/table': typeof TableRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/clubs': typeof ClubsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/predictor': typeof PredictorRoute
  '/scorers': typeof ScorersRoute
  '/table': typeof TableRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/fixtures'
    | '/gallery'
    | '/news'
    | '/predictor'
    | '/scorers'
    | '/table'
    | '/clubs/$clubId'
    | '/clubs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/fixtures'
    | '/gallery'
    | '/news'
    | '/predictor'
    | '/scorers'
    | '/table'
    | '/clubs/$clubId'
    | '/clubs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/fixtures'
    | '/gallery'
    | '/news'
    | '/predictor'
    | '/scorers'
    | '/table'
    | '/clubs/$clubId'
    | '/clubs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  FixturesRoute: typeof FixturesRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  PredictorRoute: typeof PredictorRoute
  ScorersRoute: typeof ScorersRoute
  TableRoute: typeof TableRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorers': {
      id: '/scorers'
      path: '/scorers'
      fullPath: '/scorers'
      preLoaderRoute: typeof ScorersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  FixturesRoute: FixturesRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  PredictorRoute: PredictorRoute,
  ScorersRoute: ScorersRoute,
  TableRoute: TableRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  ClubsIndexRoute: ClubsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
