/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MatchcomRouteImport } from './routes/matchcom'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as TableRouteImport } from './routes/table'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as FixturesFixtureIdRouteImport } from './routes/fixtures.$fixtureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchcomRoute = MatchcomRouteImport.update({
  id: '/matchcom',
  path: '/matchcom',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdRoute = FixturesFixtureIdRouteImport.update({
  id: '/$fixtureId',
  path: '/$fixtureId',
  getParentRoute: () => FixturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/discipline': typeof DisciplineRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/matchcom': typeof MatchcomRoute
  '/news': typeof NewsRoute
  '/predictor': typeof PredictorRoute
  '/scoreboard': typeof ScoreboardRoute
  '/table': typeof TableRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/discipline': typeof DisciplineRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/matchcom': typeof MatchcomRoute
  '/news': typeof NewsRoute
  '/predictor': typeof PredictorRoute
  '/scoreboard': typeof ScoreboardRoute
  '/table': typeof TableRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/clubs': typeof ClubsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/discipline': typeof DisciplineRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/matchcom': typeof MatchcomRoute
  '/news': typeof NewsRoute
  '/predictor': typeof PredictorRoute
  '/scoreboard': typeof ScoreboardRoute
  '/table': typeof TableRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/discipline'
    | '/fixtures'
    | '/gallery'
    | '/matchcom'
    | '/news'
    | '/predictor'
    | '/scoreboard'
    | '/table'
    | '/clubs/$clubId'
    | '/fixtures/$fixtureId'
    | '/clubs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/discipline'
    | '/fixtures'
    | '/gallery'
    | '/matchcom'
    | '/news'
    | '/predictor'
    | '/scoreboard'
    | '/table'
    | '/clubs/$clubId'
    | '/fixtures/$fixtureId'
    | '/clubs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/discipline'
    | '/fixtures'
    | '/gallery'
    | '/matchcom'
    | '/news'
    | '/predictor'
    | '/scoreboard'
    | '/table'
    | '/clubs/$clubId'
    | '/fixtures/$fixtureId'
    | '/clubs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DisciplineRoute: typeof DisciplineRoute
  FixturesRoute: typeof FixturesRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  MatchcomRoute: typeof MatchcomRoute
  NewsRoute: typeof NewsRoute
  PredictorRoute: typeof PredictorRoute
  ScoreboardRoute: typeof ScoreboardRoute
  TableRoute: typeof TableRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchcom': {
      id: '/matchcom'
      path: '/matchcom'
      fullPath: '/matchcom'
      preLoaderRoute: typeof MatchcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId': {
      id: '/fixtures/$fixtureId'
      path: '/$fixtureId'
      fullPath: '/fixtures/$fixtureId'
      preLoaderRoute: typeof FixturesFixtureIdRouteImport
      parentRoute: typeof FixturesRoute
    }
  }
}

interface FixturesRouteChildren {
  FixturesFixtureIdRoute: typeof FixturesFixtureIdRoute
}

const FixturesRouteChildren: FixturesRouteChildren = {
  FixturesFixtureIdRoute: FixturesFixtureIdRoute,
}

const FixturesRouteWithChildren = FixturesRoute._addFileChildren(
  FixturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DisciplineRoute: DisciplineRoute,
  FixturesRoute: FixturesRouteWithChildren,
  GalleryRoute: GalleryRoute,
  MatchcomRoute: MatchcomRoute,
  NewsRoute: NewsRoute,
  PredictorRoute: PredictorRoute,
  ScoreboardRoute: ScoreboardRoute,
  TableRoute: TableRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  ClubsIndexRoute: ClubsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
