CREATE TABLE public.admins (
  user_id uuid PRIMARY KEY,
  email text,
  approved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.admins TO authenticated;
GRANT ALL ON public.admins TO service_role;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_approved_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.admins WHERE user_id = auth.uid() AND approved = true);
$$;

CREATE POLICY "admins read own row" ON public.admins FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_approved_admin());
CREATE POLICY "request admin access" ON public.admins FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() AND approved = false);
CREATE POLICY "approved admins manage admins" ON public.admins FOR UPDATE TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.clubs (
  id text PRIMARY KEY,
  name text NOT NULL,
  venue text,
  crest_url text
);
GRANT SELECT ON public.clubs TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.clubs TO authenticated;
GRANT ALL ON public.clubs TO service_role;
ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read clubs" ON public.clubs FOR SELECT USING (true);
CREATE POLICY "admins manage clubs" ON public.clubs FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.table_rows (
  club_id text PRIMARY KEY REFERENCES public.clubs(id) ON DELETE CASCADE,
  p int NOT NULL DEFAULT 0,
  w int NOT NULL DEFAULT 0,
  d int NOT NULL DEFAULT 0,
  l int NOT NULL DEFAULT 0,
  gf int NOT NULL DEFAULT 0,
  ga int NOT NULL DEFAULT 0
);
GRANT SELECT ON public.table_rows TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.table_rows TO authenticated;
GRANT ALL ON public.table_rows TO service_role;
ALTER TABLE public.table_rows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read table_rows" ON public.table_rows FOR SELECT USING (true);
CREATE POLICY "admins manage table_rows" ON public.table_rows FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.scorers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name text NOT NULL,
  club_id text REFERENCES public.clubs(id) ON DELETE SET NULL,
  goals int NOT NULL DEFAULT 0
);
GRANT SELECT ON public.scorers TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.scorers TO authenticated;
GRANT ALL ON public.scorers TO service_role;
ALTER TABLE public.scorers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read scorers" ON public.scorers FOR SELECT USING (true);
CREATE POLICY "admins manage scorers" ON public.scorers FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.fixtures (
  id text PRIMARY KEY,
  match_no text,
  date date NOT NULL,
  home_id text REFERENCES public.clubs(id),
  away_id text REFERENCES public.clubs(id),
  venue text,
  kickoff text,
  home_score int,
  away_score int
);
GRANT SELECT ON public.fixtures TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fixtures TO authenticated;
GRANT ALL ON public.fixtures TO service_role;
ALTER TABLE public.fixtures ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read fixtures" ON public.fixtures FOR SELECT USING (true);
CREATE POLICY "admins manage fixtures" ON public.fixtures FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.squads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id text REFERENCES public.clubs(id) ON DELETE CASCADE,
  player_name text NOT NULL,
  jersey_no int,
  photo_url text
);
GRANT SELECT ON public.squads TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.squads TO authenticated;
GRANT ALL ON public.squads TO service_role;
ALTER TABLE public.squads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read squads" ON public.squads FOR SELECT USING (true);
CREATE POLICY "admins manage squads" ON public.squads FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag text,
  title text NOT NULL,
  body text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.news TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.news TO authenticated;
GRANT ALL ON public.news TO service_role;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read news" ON public.news FOR SELECT USING (true);
CREATE POLICY "admins manage news" ON public.news FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.albums (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.albums TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.albums TO authenticated;
GRANT ALL ON public.albums TO service_role;
ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read albums" ON public.albums FOR SELECT USING (true);
CREATE POLICY "admins manage albums" ON public.albums FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.gallery (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url text NOT NULL,
  caption text,
  sort_order int NOT NULL DEFAULT 0,
  album_id bigint REFERENCES public.albums(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.gallery TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gallery TO authenticated;
GRANT ALL ON public.gallery TO service_role;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read gallery" ON public.gallery FOR SELECT USING (true);
CREATE POLICY "admins manage gallery" ON public.gallery FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

CREATE TABLE public.settings (
  id int PRIMARY KEY DEFAULT 1,
  season_label text,
  as_of_label text,
  CONSTRAINT single_row CHECK (id = 1)
);
GRANT SELECT ON public.settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.settings TO authenticated;
GRANT ALL ON public.settings TO service_role;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "admins manage settings" ON public.settings FOR ALL TO authenticated USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

INSERT INTO public.settings (id, season_label, as_of_label)
  VALUES (1, 'Season 2026 — 5th Edition', 'as at August 2026');