-- =====================================================================
-- MTWAPA PREMIER LEAGUE — HANDWRITTEN RULE-BOOK INTEGRATION
-- Adds: match official + Man of the Match + lineups on fixtures,
-- a cards/discipline table, sponsors, and footer/settings fields
-- (social links + edition label for the copyright line).
-- Run this ONCE against the same Supabase project referenced in .env.
-- =====================================================================

-- ---------- fixtures: match official, MOTM, lineups ----------
ALTER TABLE public.fixtures
  ADD COLUMN IF NOT EXISTS match_official text,
  ADD COLUMN IF NOT EXISTS man_of_the_match text,
  ADD COLUMN IF NOT EXISTS home_lineup text,
  ADD COLUMN IF NOT EXISTS away_lineup text;

COMMENT ON COLUMN public.fixtures.match_official IS 'Referee / match official name (notes: "Indicate the Plan of the Match Official").';
COMMENT ON COLUMN public.fixtures.man_of_the_match IS 'Man of the Match player name.';
COMMENT ON COLUMN public.fixtures.home_lineup IS 'Free-text starting XI + subs for the home side.';
COMMENT ON COLUMN public.fixtures.away_lineup IS 'Free-text starting XI + subs for the away side.';

-- ---------- cards / discipline ----------
CREATE TABLE IF NOT EXISTS public.cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id text REFERENCES public.fixtures(id) ON DELETE CASCADE,
  club_id text REFERENCES public.clubs(id) ON DELETE SET NULL,
  player_name text NOT NULL,
  card_type text NOT NULL CHECK (card_type IN ('yellow', 'red')),
  -- true when a red card was shown as a result of a 2nd yellow in the same match
  red_via_two_yellows boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.cards TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cards TO authenticated;
GRANT ALL ON public.cards TO service_role;
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read cards" ON public.cards FOR SELECT USING (true);
CREATE POLICY "admins manage cards" ON public.cards FOR ALL TO authenticated
  USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

-- ---------- sponsors ----------
CREATE TABLE IF NOT EXISTS public.sponsors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  logo_url text,
  link text,
  sort_order int NOT NULL DEFAULT 0
);

GRANT SELECT ON public.sponsors TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sponsors TO authenticated;
GRANT ALL ON public.sponsors TO service_role;
ALTER TABLE public.sponsors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read sponsors" ON public.sponsors FOR SELECT USING (true);
CREATE POLICY "admins manage sponsors" ON public.sponsors FOR ALL TO authenticated
  USING (public.is_approved_admin()) WITH CHECK (public.is_approved_admin());

-- ---------- settings: footer / copyright / social links ----------
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS edition_label text DEFAULT '5th Edition',
  ADD COLUMN IF NOT EXISTS facebook_url text,
  ADD COLUMN IF NOT EXISTS instagram_url text,
  ADD COLUMN IF NOT EXISTS twitter_url text,
  ADD COLUMN IF NOT EXISTS whatsapp_url text;

-- ---------- albums: link matchday photo folders to a fixture ----------
ALTER TABLE public.albums
  ADD COLUMN IF NOT EXISTS fixture_id text REFERENCES public.fixtures(id) ON DELETE SET NULL;

-- ---------- realtime ----------
ALTER PUBLICATION supabase_realtime ADD TABLE public.cards, public.sponsors;

-- ---------- auto-computed league table ("table logic" notes) ----------
-- Notes: "1 win = 3pts, 1 draw = 1pt, 1 loss = 0pt", "number of goals
-- scored/conceded added to GF/GA", "after every game played [P] should
-- increase by +1", "everything above should reflect on the live table".
-- Rather than trusting a manually-typed table_rows row to stay in sync,
-- P/W/D/L/GF/GA are now recalculated straight from fixtures.home_score /
-- fixtures.away_score every time a fixture is saved. Pts/GD/rank stay
-- derived client-side in src/lib/league.ts (3/1/0 scoring, sort by
-- pts → GD → GF), so nothing else needs to change to "reflect on the
-- live table" — win/draw/loss/goal totals just stay correct automatically.
--
-- NB: because of this, editing a row directly on the admin "Table" tab
-- will be overwritten the next time any fixture is added/edited/deleted.
-- Use the Fixtures tab (enter the score) as the source of truth; the
-- Table tab is left in place for one-off corrections/backfills only.
CREATE OR REPLACE FUNCTION public.recalc_table_rows()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.table_rows;

  INSERT INTO public.table_rows (club_id, p, w, d, l, gf, ga)
  SELECT
    c.id,
    COALESCE(count(r.club_id), 0),
    COALESCE(sum(CASE WHEN r.gf_ > r.ga_ THEN 1 ELSE 0 END), 0),
    COALESCE(sum(CASE WHEN r.gf_ = r.ga_ THEN 1 ELSE 0 END), 0),
    COALESCE(sum(CASE WHEN r.gf_ < r.ga_ THEN 1 ELSE 0 END), 0),
    COALESCE(sum(r.gf_), 0),
    COALESCE(sum(r.ga_), 0)
  FROM public.clubs c
  LEFT JOIN (
    SELECT home_id AS club_id, home_score AS gf_, away_score AS ga_
    FROM public.fixtures
    WHERE home_score IS NOT NULL AND away_score IS NOT NULL AND home_id IS NOT NULL
    UNION ALL
    SELECT away_id AS club_id, away_score AS gf_, home_score AS ga_
    FROM public.fixtures
    WHERE home_score IS NOT NULL AND away_score IS NOT NULL AND away_id IS NOT NULL
  ) r ON r.club_id = c.id
  GROUP BY c.id;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS fixtures_recalc_table ON public.fixtures;
CREATE TRIGGER fixtures_recalc_table
  AFTER INSERT OR UPDATE OR DELETE ON public.fixtures
  FOR EACH STATEMENT EXECUTE FUNCTION public.recalc_table_rows();

-- Run it once now so any results already in fixtures are reflected immediately.
DELETE FROM public.table_rows;
INSERT INTO public.table_rows (club_id, p, w, d, l, gf, ga)
SELECT
  c.id,
  COALESCE(count(r.club_id), 0),
  COALESCE(sum(CASE WHEN r.gf_ > r.ga_ THEN 1 ELSE 0 END), 0),
  COALESCE(sum(CASE WHEN r.gf_ = r.ga_ THEN 1 ELSE 0 END), 0),
  COALESCE(sum(CASE WHEN r.gf_ < r.ga_ THEN 1 ELSE 0 END), 0),
  COALESCE(sum(r.gf_), 0),
  COALESCE(sum(r.ga_), 0)
FROM public.clubs c
LEFT JOIN (
  SELECT home_id AS club_id, home_score AS gf_, away_score AS ga_
  FROM public.fixtures
  WHERE home_score IS NOT NULL AND away_score IS NOT NULL AND home_id IS NOT NULL
  UNION ALL
  SELECT away_id AS club_id, away_score AS gf_, home_score AS ga_
  FROM public.fixtures
  WHERE home_score IS NOT NULL AND away_score IS NOT NULL AND away_id IS NOT NULL
) r ON r.club_id = c.id
GROUP BY c.id;
